http:
  routers:
    tourin-api:
      rule: "Host(`api.example.com`)"
      entryPoints:
        - web
      service: tourin-api-svc
      priority: 1

    tourin-api-limited:
      rule: "Host(`api.example.com`) && Path(`/api/route`)"
      entryPoints:
        - web
      service: tourin-api-svc
      priority: 10
      middlewares:
        - tourin-api-ratelimit

    tourin-traefik-dashboard:
      rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      entryPoints:
        - traefik
      service: api@internal

  middlewares:
    tourin-api-ratelimit:
      rateLimit:
        average: 30
        burst: 60
        period: 1s
        sourceCriterion:
          requestHeaderName: CF-Connecting-IP

  services:
    tourin-api-svc:
      loadBalancer:
        servers:
          - url: "http://api:5000"
